apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-nginx
spec:
  containers:
   - name: csi-s3-test-nginx
     image: nginx
     volumeMounts:
       - mountPath: /usr/share/nginx/html/s3
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: csi-s3-manual-pvc         # manualbucket-with-path csi-s3-manual-pvc
       readOnly: false
