apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: default
stringData:
  accessKeyID: "AKIA57OPXNFOCLIJA3F2"
  secretAccessKey: "UDTPG047ih6oShaeWsKRVr/w2ItET8S9j8nZotGvW"
  # For AWS set it to "https://s3.<region>.amazonaws.com", for example https://s3.eu-central-1.amazonaws.com
  endpoint: "https://s3.ap-south-1.amazonaws.com"
  # For AWS set it to AWS region
  region: "ap-south-1"
